version: "3.8"

services:
  api:
    build: .
    container_name: api-back
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: clickcannabis
      DB_PASSWORD: 123456
      DB_DATABASE: services
      DB_SYNCHRONIZE: "true"
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: clickcannabis
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: services
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
